### ISSUE TITLE
Use rustls instead of OpenSSL

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#255]
- use `rustls`: https://github.com/actix/actix-web/blob/604be5495f920a9f11056fad989ff757ed364f2b/actix-http/Cargo.toml#L30
- Modify the dockerfile accordingly (remove useless dependencies)

**Comment by Kerollmops** [comment]
I am not sure I understand why you were compiling openssl @curquiza because we already use the `rustls` feature of `actix-web`:

https://github.com/meilisearch/transplant/blob/261df4b38612fb56ebd1adf49e6f69707d442a8d/meilisearch-http/Cargo.toml#L26-L28

Ok, that's due to our `reqwest` `build-dependency` that uses `native-tls`, which means that it tries to use openssl. We should use [the `rustls-tls` feature](https://docs.rs/reqwest/0.11.4/reqwest/#optional-features) here too!

**Comment by irevoire** [comment]
That was my mistake :innocent:
